SportsStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

SportsStore.WebUI/Models/ProductsListViewModel.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ProductsListViewModel.cs" company="The Advisory Board Company">
//   Copyright 2010-2011
// </copyright>
// <summary>
//   Defines the ProductsListViewModel type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace SportsStore.WebUI.Models
{
    using System.Collections.Generic;
    using SportsStore.Domain.Entities;

    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }

        public PagingInfo PagingInfo { get; set; }

        public string CurrentCategory { get; set; }
        

    }
}

SportsStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository productRepository;
        //
        // GET: /Cart/

        /// <summary>
        /// Creates and instance of the product Cart Controller class.
        /// </summary>
        /// <param name="productRepository"></param>
        public CartController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

       
        public ViewResult Index(string returnUrl, Cart cart)
        {
            var cartIndexModel = new CartIndexViewModel
                                     {
                                         Cart = cart,
                                         ReturnUrl = returnUrl
                                     };
            return this.View(cartIndexModel);
        }

        [HttpPost]
        public RedirectToRouteResult AddToCart(int? productId, string returnUrl, Cart cart)
        {
            if (productId.HasValue)
            { 
                Product product = this.productRepository.Products
                    .FirstOrDefault(p => p.ProductId == productId.Value);

                if (product != null)
                {
                    cart.AddItem(product,1);
                }
            }
            return RedirectToAction("Index", new {returnUrl});
        }
        
        [HttpPost]
        public RedirectToRouteResult RemoveFromCart(int? productId, string returnUrl, Cart cart)
        {
            if (productId.HasValue)
            { 
                Product product = this.productRepository.Products
                    .FirstOrDefault(p => p.ProductId == productId.Value);

                if (product != null)
                {
                    cart.RemoveLine(product);
                }
            }
            return this.RedirectToAction("Index", new {returnUrl});
        }

        public ViewResult Summary(Cart cart)
        {
            return this.View("Summary",cart);
        }

        public ViewResult Checkout()
        {
            return this.View(new ShippingDetails());
        }
    }
}

SportsStore.WebUI/Controllers/NavController.cs
namespace SportsStore.WebUI.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using SportsStore.Domain.Abstract;

    public class NavController : Controller
    {
        private IProductRepository repository;
       
        public NavController(IProductRepository repo)
        {
            this.repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                    .Select(x => x.Category)
                    .OrderBy(x => x).ToList();

            return this.PartialView(categories.Distinct());

        }

        
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
namespace SportsStore.WebUI.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using SportsStore.Domain.Abstract;
    using SportsStore.WebUI.Models;
    //using log4net;
    using Common.Logging;

    public class ProductController : Controller
    {
        private readonly IProductRepository repository;

        public int PageSize = 4;
        private ILog logger;

        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
            //logger = log4net.LogManager.GetLogger("General");
            logger = LogManager.GetLogger("General");
        }

        public ViewResult List(string category, int page = 1)
        {
            
            ProductsListViewModel viewModel = new ProductsListViewModel
                {
                    Products = this.repository.Products
                    .OrderBy(p => p.ProductId)
                    .Where(p => string.IsNullOrWhiteSpace(category) || p.Category == category)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                    PagingInfo = new PagingInfo
                        {
                            CurrentPage = page,
                            ItemsPerPage = PageSize,
                            TotalItems = category == null ?
                            repository.Products.Count() :
                            repository.Products.Where(x => x.Category == category).Count()
                        },
                    CurrentCategory = category
                };

            return View(viewModel);
        }

        public ViewResult NewPage()
        {
            return this.View();
        }
    }
}

SportsStore.WebUI/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetails
@{
    ViewBag.Title = "SportsStore: Checkout";
}
<h2>
    Check out now</h2>
Please enter your details, and we'll ship your goods right away!
@using (Html.BeginForm())
{ 
    <h3>
        Ship to</h3>
    <div>
        Name: @Html.EditorFor(x => x.Name)</div>
    <h3>
        Address</h3>
    <div>
        Line 1: @Html.EditorFor(x => x.Line1)
    </div>
    <div>
        Line 2: @Html.EditorFor(x => x.Line2)
    </div>
    <div>
        Line 3: @Html.EditorFor(x => x.Line3)
    </div>
    <div>
        City: @Html.EditorFor(x => x.City)
    </div>
    <div>
        State: @Html.EditorFor(x => x.State)</div>
    <div>
        Zip: @Html.EditorFor(x => x.Zip)</div>
    <div>
        Country: @Html.EditorFor(x => x.Country)</div>
    <h3>
        Options</h3>
    <label>
        @Html.EditorFor(x => x.GiftWrap)
        Gift wrap these items
    </label>
    <p align="center">
        <input class="actionButtons" type="submit" value="Complete order" />
    </p>
}

SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel
@{
    ViewBag.Title = "Sports Store: Your Cart";
}
<h2>
    Your Cart</h2>
<table width="90%" align="center">
    <thead>
        <tr>
            <th align="center">
                Quantity
            </th>
            <th align="left">
                Item
            </th>
            <th align="right">
                Price
            </th>
            <th align="right">
                Subtotal
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        { 
            <tr>
                <td align="center">@line.Quantity
                </td>
                <td align="left">@line.Product.Name
                </td>
                <td align="right">@line.Product.Price.ToString("c")
                </td>
                <td align="right">@((line.Quantity * line.Product.Price).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="actionButtons" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">
                Total:
            </td>
            <td align="right">@Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<p align="center" class="actionButtons">
    <a href="@Model.ReturnUrl">Continue Shopping</a>
    @Html.ActionLink("Checkout now","Checkout")
</p>

SportsStore.WebUI/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart
@{Layout = null;}
<div id="cart">
    <span class="caption"><b>Your cart:</b>
        @Model.Lines.Sum(x => x.Quantity) item(s),
        @Model.ComputeTotalValue().ToString("c")
    </span>
    @Html.ActionLink("Checkout", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, null)
</div>

SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>
@{
    Layout = null;
}
@Html.ActionLink("Home", "List", "Product")
@foreach (var link in Model) {
    @Html.RouteLink(link, new
{
    controller = "Product",
    action = "List",
    category = link,
    page = 1
}, new { @class = link == ViewBag.selectedCategory ? "selected" : null })}

SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel
@using SportsStore.WebUI.HtmlHelpers
@{
    ViewBag.Title = "Products";
}
<h2>
    List</h2>
@foreach (var p in Model.Products)
{
    Html.RenderPartial("_ProductSummary", p);
}
<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>
<body>
    <div id="header">
        @{Html.RenderAction("Summary", "Cart");}
        <div class="title">
            SPORTS STORE</div>
    </div>
    <div id="categories">
        @{Html.RenderAction("Menu", "Nav");}
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product
<div class="item">
    <h3>@Model.Name</h3>
    @Model.Description
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        @Html.HiddenFor(x=>x.ProductId)
        @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
        <input type="submit" value="+ Add to cart" />
    }

    <h4>@Model.Price.ToString("c")</h4>
</div>